spring:
  application:
    name: firstSpringBoot
  datasource:
      url: jdbc:mysql://localhost:3306/mystore?createDatabaseIfNotExist=true
      username: root
      password: ng195626
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

